# Generated by Django 5.1.1 on 2024-09-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.userprofile')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.reply')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('created_by', 'reply'), name='unique_reply_like')],
            },
        ),
    ]
