# Generated by Django 4.2.12 on 2024-09-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0005_alter_reply_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replylike',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to='socialMedia.reply'),
        ),
    ]
