# Generated by Django 5.1.1 on 2024-10-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0006_alter_replylike_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='socialMedia.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('created_by', 'post'), name='unique_dislike')],
            },
        ),
    ]
