# Generated by Django 5.1.1 on 2024-10-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0007_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
